/// قائمة اللغات المدعومة في التطبيق (رمز + اسم العرض).
const List<({String code, String name})> kWorldLanguages = [
  (code: 'en', name: 'English'),
  (code: 'ar', name: 'العربية'),
  (code: 'es', name: 'Español'),
  (code: 'fr', name: 'Français'),
  (code: 'de', name: 'Deutsch'),
  (code: 'zh', name: '中文'),
  (code: 'hi', name: 'हिन्दी'),
  (code: 'pt', name: 'Português'),
  (code: 'ru', name: 'Русский'),
  (code: 'ja', name: '日本語'),
  (code: 'ko', name: '한국어'),
  (code: 'it', name: 'Italiano'),
  (code: 'tr', name: 'Türkçe'),
  (code: 'vi', name: 'Tiếng Việt'),
  (code: 'th', name: 'ไทย'),
  (code: 'id', name: 'Bahasa Indonesia'),
  (code: 'nl', name: 'Nederlands'),
  (code: 'pl', name: 'Polski'),
  (code: 'uk', name: 'Українська'),
  (code: 'ro', name: 'Română'),
  (code: 'hu', name: 'Magyar'),
  (code: 'el', name: 'Ελληνικά'),
  (code: 'he', name: 'עברית'),
  (code: 'fa', name: 'فارسی'),
  (code: 'ur', name: 'اردو'),
  (code: 'bn', name: 'বাংলা'),
  (code: 'sw', name: 'Kiswahili'),
  (code: 'sv', name: 'Svenska'),
  (code: 'da', name: 'Dansk'),
  (code: 'no', name: 'Norsk'),
  (code: 'fi', name: 'Suomi'),
  (code: 'cs', name: 'Čeština'),
  (code: 'sk', name: 'Slovenčina'),
  (code: 'bg', name: 'Български'),
  (code: 'hr', name: 'Hrvatski'),
  (code: 'sr', name: 'Српски'),
  (code: 'ms', name: 'Bahasa Melayu'),
  (code: 'tl', name: 'Filipino'),
  (code: 'ta', name: 'தமிழ்'),
  (code: 'te', name: 'తెలుగు'),
  (code: 'mr', name: 'मराठी'),
  (code: 'gu', name: 'ગુજરાતી'),
  (code: 'kn', name: 'ಕನ್ನಡ'),
  (code: 'ml', name: 'മലയാളം'),
  (code: 'pa', name: 'ਪੰਜਾਬੀ'),
  (code: 'am', name: 'አማርኛ'),
  (code: 'ha', name: 'Hausa'),
  (code: 'yo', name: 'Yorùbá'),
  (code: 'ig', name: 'Igbo'),
  (code: 'zu', name: 'isiZulu'),
  (code: 'af', name: 'Afrikaans'),
  (code: 'ca', name: 'Català'),
  (code: 'eu', name: 'Euskara'),
  (code: 'gl', name: 'Galego'),
];
